//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpInfo
    {
        public string EmailId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<int> PassCode { get; set; }
    }
}
